=== raouf505/cbm-posx/src/main/resources/xsd/jibx/navigation.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:tns="http://jibx.org/starter" elementFormDefault="qualified"
	targetNamespace="http://jibx.org/starter">

	<xs:element name="navigation" type="tns:navigation" />

	<xs:complexType name="navigation">
		<xs:annotation>
			<xs:documentation>Global Navigation</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="link" type="tns:link" minOccurs="1" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="link">
		<xs:sequence>
			<xs:element name="id" type="xs:string" minOccurs="1" />
			<xs:element name="text" type="xs:string" minOccurs="1" />
			<xs:element name="href" type="xs:string" minOccurs="1" />
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== raouf505/cbm-posx/src/main/resources/xml/en-CR/navigation.xml
<?xml version="1.0" encoding="UTF-8"?>
<navigation xmlns="http://jibx.org/starter" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.w3.org/2001/XMLSchema-instance ../../../xsd/jibx/navigation.xsd">
	
	<link>
		<id>inventory</id>
		<text>Inventario</text>
		<href>/inventory/show</href>
	</link>
	
	<link>
		<id>checkIn</id>
		<text>Facturaci√≥n</text>
		<href>/checkIn</href>
	</link>

</navigation>
